### ISSUE TITLE
Refactor Needed For Modal Component

### ISSUE THREAD

**Issue by Rubix982** [Terrabuzz/Terrabuzz#101]
**Is your suggestion related to something in the UI design of the website?**
Yes. The Modal component for the Profile needs to be refactored.

**Is your suggestion related to the database design?**
No

**Describe the solution you'd like**
No

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by hassanzhd** [comment]
You need a close button here

**Comment by Rubix982** [comment]
Closing. Not really that important.
