### ISSUE TITLE
Add notification and log out dropdown

### ISSUE THREAD

**Issue by Rubix982** [Terrabuzz/Terrabuzz#105]
**Is your feature request related to a problem? Please describe.**
There should a dropdown for the notifications and a dropdown for the logout.

**Describe the solution you'd like**
Just add a dropdown

**Describe alternatives you've considered**
Adding a dropdown, DUUHHH

**Additional context**
Nah.

**Comment by hassanzhd** [comment]
This is done right?

**Comment by Rubix982** [comment]
Yes.
