### ISSUE TITLE
Implement POST requests for comment and likes

### ISSUE THREAD

**Issue by hassanzhd** [Terrabuzz/Terrabuzz#110]
implementations must be done of comment and like additon endpoints on the server for enabling the user to add and like posts

**Comment by hassanzhd** [comment]
Likes implemented!

**Comment by Rubix982** [comment]
Ye bas in dono cheetah logon ka kamal hai, @TashikMoin23 @hassanzhd

**Comment by hassanzhd** [comment]
Comments are still left to be implemented as a unit

**Comment by Rubix982** [comment]
Closing this. Opening a new issue just for the comments.
