### ISSUE TITLE
Generating Profile Pages Based on User's Handle

### ISSUE THREAD

**Issue by Rubix982** [Terrabuzz/Terrabuzz#125]
**Is your suggestion related to something in the UI design of the website?**
Each user should have a separate profile page

**Is your suggestion related to the database design?**
It's just a static page at the moment

**Describe the solution you'd like**
Have a separate page for each user!

**Comment by hassanzhd** [comment]
Implemented in: Profile feature completed and DDL updated on server #147

**Comment by Rubix982** [comment]
#147 is merged and approved. Closing.
